Make the log filename depend on COMPONENT in mirror-kali-images
Now that we can have several instances of the script running at once,
with different config files, we need to make sure that each instance
with log to a different log file.

The most obvious is just to re-use the COMPONENT in the log file name,
which is already what's done anyway with the default component
kali-images.

Additionally, this commit embeds the 'log/' directory in the variable,
it seems less error prone this way, We already embed the 'etc/'
directory in the CONFIG_FILE variable above, so let's follow this style
consistently.

diff --git a/bin/mirror-kali-images b/bin/mirror-kali-images
--- a/bin/mirror-kali-images
+++ b/bin/mirror-kali-images
@@ -69,18 +69,20 @@ else
 fi
 
 # Prepare before running
+LOG_FILE=log/rsync-"$COMPONENT".log
+ERROR_FILE=log/rsync-"$COMPONENT".error
 mkdir -p log
 
 # Run the sync
 rsync $RSYNC_OPTIONS $RSYNC_URL $TO \
-      >log/rsync-kali-images.log 2>log/rsync-kali-images.error || err=$?
+      >"$LOG_FILE" 2>"$ERROR_FILE" || err=$?
 
 if [ "$err" -ne "0" ]; then
         echo "ERROR: rsync $RSYNC_URL $TO failed" >&2
-        echo "See $(pwd)/log/rsync-kali-images.error.0 for details" >&2
+        echo "See $(pwd)/$ERROR_FILE.0 for details" >&2
 fi
 
-savelog log/rsync-kali-images.log
-savelog log/rsync-kali-images.error
+savelog "$LOG_FILE"
+savelog "$ERROR_FILE"
 
 exit $err
